//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandCommittee.AppData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LandCommittee_Entities : DbContext
    {
        public LandCommittee_Entities()
            : base("name=LandCommittee_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoryLand> CategoryLand { get; set; }
        public virtual DbSet<categoryOwner> categoryOwner { get; set; }
        public virtual DbSet<ContractOfSale> ContractOfSale { get; set; }
        public virtual DbSet<Culculation> Culculation { get; set; }
        public virtual DbSet<LandPlot> LandPlot { get; set; }
        public virtual DbSet<LeaseContract> LeaseContract { get; set; }
        public virtual DbSet<Owner> Owner { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
