//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandCommittee.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaseContract
    {
        public int id { get; set; }
        public int idLandPlot { get; set; }
        public int idTenat { get; set; }
        public System.DateTime startContract { get; set; }
        public System.DateTime endContract { get; set; }
        public int idCalculation { get; set; }
        public float sumCost { get; set; }
        public bool isDeleted { get; set; }
        public string actualUse { get; set; }
        public string fixing { get; set; }
        public float BAP { get; set; }
    
        public virtual Culculation Culculation { get; set; }
        public virtual LandPlot LandPlot { get; set; }
        public virtual Owner Owner { get; set; }
    }
}
